apiVersion: performance.openshift.io/v2
kind: PerformanceProfile
metadata:
  # if you change this name make sure the 'include' line in TunedPerformancePatch.yaml
  # matches this name: include=openshift-node-performance-${PerformanceProfile.metadata.name}
  # Also in file 'validatorCRs/informDuValidator.yaml': 
  # name: 50-performance-${PerformanceProfile.metadata.name}
  name: openshift-node-performance-profile
  annotations:
    ran.openshift.io/ztp-deploy-wave: "10"
    ran.openshift.io/reference-configuration: "ran-du.redhat.com"
spec:
  additionalKernelArgs:
    - rcupdate.rcu_normal_after_boot=0
    - efi=runtime
    - vfio_pci.enable_sriov=1
    - vfio_pci.disable_idle_d3=1
    - module_blacklist=irdma
  cpu:
    isolated: {{cpu.isolated}}
    reserved: {{cpu.reserved}}
  hugepages:
    defaultHugepagesSize: 1G
    pages:
      - size: 1G
        count: 32
  machineConfigPoolSelector:
    pools.operator.machineconfiguration.openshift.io/master: ""
  hardwareTuning:
    isolatedCpuFreq: {{hardwareTuning.isolatedCpuFreq}}
    reservedCpuFreq: {{hardwareTuning.reservedCpuFreq}}
  userLevelNetworking: true
  nodeSelector:
    node-role.kubernetes.io/master: ""
  numa:
    topologyPolicy: "restricted"
  # To use the standard (non-realtime) kernel, set enabled to false
  realTimeKernel:
    enabled: true
  workloadHints:
    # WorkloadHints defines the set of upper level flags for different type of workloads.
    # See https://github.com/openshift/cluster-node-tuning-operator/blob/master/docs/performanceprofile/performance_profile.md#workloadhints
    # for detailed descriptions of each item.
    # The configuration below is set for a low latency, performance mode.
    realTime: true
    highPowerConsumption: false
    perPodPowerManagement: false
