cluster:
  domain: outbound.vz.bos2.lab
  name: sno148
  #arm, amd, intel; default is intel if not present
  platform: intel
  ntps:
    - 0.rhel.pool.ntp.org
    - 1.rhel.pool.ntp.org
  profile: ran

host:
  hostname: sno148.outbound.vz.bos2.lab
  # when bond is enabled, interface name is used for setting up bond interface
  interface: bond0
  #when bond is enabled, mac is not used, setting mac is not supported on bond interface
  #mac: b4:96:91:b4:9d:f0
  ipv4:
    enabled: true
    dhcp: false
    ip: 192.168.58.48
    dns:
      - 192.168.58.15
    gateway: 192.168.58.1
    prefix: 25
    machine_network_cidr: 192.168.58.0/25
    #optional, default 10.128.0.0/14
    #cluster_network_cidr: 10.128.0.0/14
    #optional, default 23
    #cluster_network_host_prefix: 23
  ipv6:
    enabled: false
    dhcp: false
    ip: 2600:52:7:58::48
    dns:
      - 2600:52:7:58::15
    gateway: 2600:52:7:58::1
    prefix: 64
    machine_network_cidr: 2600:52:7:58::/64
    #optional, default fd01::/48
    #cluster_network_cidr: fd01::/48
    #optional, default 64
    #cluster_network_host_prefix: 64
  # see https://docs.redhat.com/en/documentation/red_hat_enterprise_linux/8/html/configuring_and_managing_networking/configuring-network-bonding_configuring-and-managing-networking
  bond:
    enabled: true
    mode: 802.3ad
    miimon: 100
    # add bonding member by interface name and mac
    members:
      - interface: ens1f0
        mac: b4:96:91:b4:9d:f0
        #optional layer2 configuration on member
        #ethernet:
          #auto-negotiation: true
          #duplex: true
          #speed: 10000
      - interface: ens2f0
        mac: b4:96:91:b4:9e:f0
        #optional layer2 configuration on member
        #ethernet:
          #auto-negotiation: true
          #duplex: true
          #speed: 10000
  vlan:
    enabled: true
    name: vlan58
    id: 58
  disk: /dev/nvme0n1

# refer to templates/cluster-profile-full.yaml for all settings
