cluster:
  domain: outbound.vz.bos2.lab
  name: sno148
  ntps:
    - 0.rhel.pool.ntp.org
    - 1.rhel.pool.ntp.org
  profile: ran
  
host:
  hostname: sno148.outbound.vz.bos2.lab
  #Set up networking:
  #  - when "bond.enable" is set to true, "host.interface" is the name of bond interface and "host.mac" is not used;
  #    otherwise, "host.interface" and "host.mac" is used to setup ethernet interface;
  #  - when vlan.enabled is set to true, "host.interface" is used as parent interface for vlan interface "vlan.name"
  #Testing:
  # jinja2 templates/agent-config.yaml.j2 config.yaml|yq .hosts[0].networkConfig |nmstatectl gc -
  interface: ens1f0
  mac: b4:96:91:b4:9d:f0
  ipv4:
    enabled: true
    dhcp: false
    ip: 192.168.58.48
    dns:
      - 192.168.58.15
    gateway: 192.168.58.1
    prefix: 25
    machine_network_cidr: 192.168.58.0/25
    #optional, default 10.128.0.0/14
    #cluster_network_cidr: 10.128.0.0/14
    #optional, default 23
    #cluster_network_host_prefix: 23
  ipv6:
    enabled: false
    dhcp: false
    ip: 2600:52:7:58::48
    dns:
      - 2600:52:7:58::15
    gateway: 2600:52:7:58::1
    prefix: 64
    machine_network_cidr: 2600:52:7:58::/64
    #optional, default fd01::/48
    #cluster_network_cidr: fd01::/48
    #optional, default 64
    #cluster_network_host_prefix: 64
  bond:
    enabled: false
    mode: 802.3ad
    miimon: 100
    # add bonding member by interface name and mac
    members:
      - interface: ens1f0
        mac: b4:96:91:b4:9d:f0
        #optional layer2 configuration on member
        #ethernet:
          #auto-negotiation: true
          #duplex: true
          #speed: 10000
      - interface: ens2f0
        mac: b4:96:91:b4:9e:f0
        #optional layer2 configuration on member
        #ethernet:
          #auto-negotiation: true
          #duplex: true
          #speed: 10000
  vlan:
    enabled: false
    name: vlan58
    id: 58
  disk: /dev/nvme0n1

container_storage:
  enabled: true
  device: /dev/nvme0n1
  startMiB: 250000
  sizeMiB: 0

readiness:
  extra_checks:
    - ${HOME}/r1
    - ${HOME}/21



bmc:
  address: 192.168.13.148
  username: Administrator
  password: dummy
  kvm_uuid:
  
iso:
  address: http://192.168.58.15/iso/sno148.iso
  #optional, when mounting the virtual media, some hardware or redfish version may not support TransferProtocolType
  #in the API request, in that case set it as 'skip'
  #protocol: skip
  # deploy script will be called before mounting the ISO
  # arg1: generated ISO
  # arg2: .iso.address
  deploy: ${HOME}/bin/deploy_boot_iso.sh
