cluster:
  domain: outbound.vz.bos2.lab
  name: sno148
  profile: ran
  
host:
  hostname: sno148.outbound.vz.bos2.lab
  interface: ens1f0
  mac: b4:96:91:b4:9d:f0
  ipv4:
    enabled: true
    dhcp: false
    ip: 192.168.58.48
    dns:
      - 192.168.58.15
    gateway: 192.168.58.1
    prefix: 25
    machine_network_cidr: 192.168.58.0/25
  disk: /dev/nvme0n1

# omit for other settings, refer to templates/cluster-profile-full.yaml for all settings