cluster:
  domain: outbound.vz.bos2.lab
  name: sno148
  #arm, amd, intel; default is intel if not present
  platform: intel
  ntps:
    - 0.rhel.pool.ntp.org
    - 1.rhel.pool.ntp.org
  profile: ran
  
  #optional: https://docs.openshift.com/container-platform/4.14/post_installation_configuration/enabling-cluster-capabilities.html
  #if not present:
  #for 4.12 it will set:
  #baselineCapabilitySet: None
  #  additionalEnabledCapabilities:
  #      - marketplace
  # for 4.13+, it will set:
  #baselineCapabilitySet: None
  #  additionalEnabledCapabilities:
  #      - marketplace
  #      - NodeTuning
  capabilities:
    #None|vCurrent|v4.12|v4.14 ...
    baselineCapabilitySet: None
    additionalEnabledCapabilities:
      - marketplace
host:
  hostname: sno148.outbound.vz.bos2.lab
  #Set up networking:
  #  - when "bond.enable" is set to true, "host.interface" is the name of bond interface and "host.mac" is not used;
  #    otherwise, "host.interface" and "host.mac" is used to setup ethernet interface;
  #  - when vlan.enabled is set to true, "host.interface" is used as parent interface for vlan interface "vlan.name"
  #Testing:
  # jinja2 templates/agent-config.yaml.j2 config.yaml|yq .hosts[0].networkConfig |nmstatectl gc -
  interface: ens1f0
  mac: b4:96:91:b4:9d:f0
  ipv4:
    enabled: true
    dhcp: false
    ip: 192.168.58.48
    dns:
      - 192.168.58.15
    gateway: 192.168.58.1
    prefix: 25
    machine_network_cidr: 192.168.58.0/25
    #optional, default 10.128.0.0/14
    #cluster_network_cidr: 10.128.0.0/14
    #optional, default 23
    #cluster_network_host_prefix: 23
  ipv6:
    enabled: false
    dhcp: false
    ip: 2600:52:7:58::48
    dns:
      - 2600:52:7:58::15
    gateway: 2600:52:7:58::1
    prefix: 64
    machine_network_cidr: 2600:52:7:58::/64
    #optional, default fd01::/48
    #cluster_network_cidr: fd01::/48
    #optional, default 64
    #cluster_network_host_prefix: 64
  bond:
    enabled: false
    mode: 802.3ad
    miimon: 100
    # add bonding member by interface name and mac
    members:
      - interface: ens1f0
        mac: b4:96:91:b4:9d:f0
        #optional layer2 configuration on member
        #ethernet:
          #auto-negotiation: true
          #duplex: true
          #speed: 10000
      - interface: ens2f0
        mac: b4:96:91:b4:9e:f0
        #optional layer2 configuration on member
        #ethernet:
          #auto-negotiation: true
          #duplex: true
          #speed: 10000
  vlan:
    enabled: false
    name: vlan58
    id: 58
  disk: /dev/nvme0n1

day1:
  workload_partition: true
  kdump: 
    enabled: true
    #set blacklist_ice as true on HPE servers
    blacklist_ice: false
  boot_accelerate: true
  #4.13+ only, whether enable crun as default container runtime, 4.18+ will be enabled by default
  crun: true
  #4.14, https://issues.redhat.com/browse/OCPBUGS-17660
  rcu_normal: true
  #4.14, reduce a node boot and fix a race condition issue in sriov operator
  sriov_kernel: true
  #4.14, sync the node time from ntp when node reboot and ptp got involved
  sync_time_once: true
  #whether enable cgroup v1; 4.14-4.15: will enable cgv1 by default, 4.16+ will enable cgv2 by default
  cgv1: true
  # partitions for container storage
  container_storage:
    enabled: false
    device: /dev/nvme0n1
    startMiB: 250000
    sizeMiB: 0

  #ztp_hub=true will enable rhacm/lvm/gitops/talm on the cluster
  ztp_hub: false
  operators:
    ptp:
      enabled: true
      #source: prega
      #if you want to stay on a particular version ptp-operator.4.12.0-202402081808
      #version: ptp-operator.4.12.0-202402081808
    sriov:
      enabled: true
      #source: prega
      #if you want to stay on a particular version sriov-network-operator.v4.12.0-202402081808
      #version: sriov-network-operator.v4.12.0-202402081808
    local-storage:
      enabled: true
      #source: prega
      #if you want to stay on a particular version local-storage-operator.v4.12.0-202403082008
      #version: local-storage-operator.v4.12.0-202403082008
      #preparation work for local storage
      provision:
        #type: default partition if "lvs" key is not present
        #   partition: use ignition, can be done once during installation
        #   lvs: use run-once service, can be adjusted later
        type: partition
        # file system type, default xfs
        fs_type: ext4
        #Get the ID with command: udevadm info -q property --property=ID_PATH /dev/nvme1n1
        disk_by_path: pci-0000:c3:00.0-nvme-1
        # the previous lvs key is deprecated
        partitions:
          1g: 10
          2g: 10
          4g: 5
          5g: 5
          10g: 2
          15g: 1
          30g: 1
    gitops:
      #source: prega
      enabled: false
    rhacm:
      #source: prega
      enabled: false
    talm:
      #source: prega
      enabled: false
    mce:
      #source: prega
      enabled: false
    mcgh:
      #source: prega
      enabled: false
    lvm:
      #source: prega
      enabled: false
      #source: cs-redhat-operator-index
      #provision:
      #  disks:
      #    - disk_by_path: pci-0000:03:00.0-nvme-1
      #      wipe_table: true
    fec:
      #source: prega
      enabled: false
      #if you want to stay on a particular version sriov-fec.v2.7.2
      #version: sriov-fec.v2.7.2
    cluster-logging:
      #source: prega
      enabled: false
      #set the channel
      #channel: stable
      #if you want to stay on a particular version
      #version: cluster-logging.v5.8.3
    adp:
      #source: prega
      enabled: false
      #set the channel
      #channel: stable-1.3
      #set the version
      #version: 1.3.1
    lca:
      #source: prega
      enabled: false
      #set the channel
      #channel: stable
      #set the version
      #version: v4.16.0-89
    metallb:
      #source: prega
      enabled: false
    nmstate:
      #source: prega
      enabled: false
    kubevirt-hyperconverged:
      #source: prega
      enabled: false
      #channel: stable
      #set the version
      #version: v4.16.3
    nfd:
      #source: prega
      enabled: false
      #channel: stable
      #set the version
      #version:
    gpu:
      enabled: false
      #source: certified-operators
      #channel: v24.9
      #version: gpu-operator-certified.v24.9.2
    amq:
      #source: prega
      enabled: false
      #channel: amq-streams-2.9.x
      #set the version
      #version:
    amq-console:
      #source: prega
      enabled: false
      #channel: amq-streams-2.9.x
      #set the version
      #version:
  extra_manifests:
    - ${HOME}/1
    - ${HOME}/2
    - $OCP_Y_VERSION

day2:
  # pause the MCP for a certain period and unpause it in order to reduce the number of node reboot.
  delay_mcp_update: 60
  performance_profile:
    enabled: true
    template: a|b|c|d
    data:
      #in case you want to specify the performance profile name
      name: sno-perfprofile
      #optional, default value: true
      real_time: false
      #additional_kernel_args. optional
      #additional_kernel_args:
      #- 1
      #- 2
      #optional, present if want to set user_level_networking as true
      net:
        user_level_networking: true
      #optional for hardware tuning, OCP 4.16
      hardwareTuning:
        isolatedCpuFreq: 2500000
        reservedCpuFreq: 2800000
      #optional
      hugepage:
        enabled: true
        default: 2M
        pages:
          - size: 2M
            count: 32768
            #node: 1
  tuned_profile: 
    enabled: true
    profiles:
    - template: a|b|c|d
      data:
        #for wrong bios settings, if passive mode is used, set intel_pstate=active
        cmdline_pstate: intel_pstate=active
        #in case you want to generate kdump for some special scenarios (used in lab)
        kdump: false
        sysfs:
          #cap the intel_pstate peak frequency at 2.5Ghz, used in 4.14. 4.16 can set day2.performance_profile.hardwareTuning
          cpufreq_max_freq: 2500000
    - template: a|b|c|d
      data:
        #for wrong bios settings, if passive mode is used, set intel_pstate=active
        cmdline_pstate: intel_pstate=active
        #in case you want to generate kdump for some special scenarios (used in lab)
        kdump: false
        sysfs:
          #cap the intel_pstate peak frequency at 2.5Ghz, used in 4.14. 4.16 can set day2.performance_profile.hardwareTuning
          cpufreq_max_freq: 2500000
  ptp:
    #ptpconfig type: choose any of them: disabled|ordinary|boundary
    #chronyd service will be disabled if ordinary or boundary being selected
    ptpconfig: disabled
    clock_threshold_tuning:
      hold_over_timeout: 5
      max_offset: 500
      min_offset: -500
    ordinary_clock:
      #name: crdu-ptp-ordinary-clock
      interface: ens1f0
    boundary_clock:
      # only supported for 4.16+, when not enabled, the profiles[0] is used for system clock, 4.15 or earlier versions must set it as false
      ha_enabled: false
      #name (default): crdu-boundary-clock-ptp-config
      #name: crdu-boundary-clock-ptp-config
      profiles:
      - name: bc-profile-nic1
        slave: ens1f0
        masters:
          - ens1f1
          - ens1f2
          - ens1f3
        ptp4lConf:
          boundary_clock_jbod: 0
      - name: bc-profile-nic2
        slave: ens2f0
        masters:
          - ens2f1
          - ens2f2
          - ens2f3
        ptp4lConf:
          boundary_clock_jbod: 0

    #enable the ptp event, if true, will set summary_interval as -4, otherwise it will stay at 0
    enable_ptp_event: true
    #event_api_version: "1.0" or "2.0"; to avoid issues, 4.12-4.15, should not set event_api_version
    #4.16-4.17, if event_api_version not present, "1.0" will be the default
    #4.18, if event_api_version not present, "2.0" will be the default
    #4.19+, "1.0" will be deleted
    #event_api_version: "1.0"
    #enable log_reduce, when setting as true it will reduce(filter all) the ptp logs
    log_reduce: true

  #enable the cluster monitoring tuning
  cluster_monitor_tuning: true
  #disable the network diagnostics
  disable_network_diagnostics: true
  #4.14 disable the olm pprof(collect-profile cronjob)
  disable_olm_pprof: true
  disable_operator_auto_upgrade: true

  #https://github.com/openshift-kni/cnf-features-deploy/blob/master/ztp/source-crs/SriovOperatorConfig-SetSelector.yaml
  sriov:
    enable_injector: false
    enable_webhook: false

  lvm:
    device_classes:
      - name: "sno"
        default: true
        thin_pool_name: "sno-sdb-pool"
        selector:
          paths:
            - "/dev/sdb"
  #LocalVolume settings for local storage operator,
  #if not present, and if day1.operators.local-storage.provision.lvs is present, will use default name 'local-disks'
  # and storageClassName 'general'
  local_storage:
    local_volume:
      name: local-disks
      storageClassName: general

  extra_manifests:
    - ${HOME}/1
    - ${HOME}/2
    - $OCP_Y_VERSION

# support additional readiness script in folders
#   script
#      should have .sh extention
#      return 0 if successfull
#      return none zero if failed
#      all output will be captured and displayed
readiness:
  extra_checks:
    - ${HOME}/r1
    - ${HOME}/21

cpu:
  isolated: 2-31,34-63
  reserved: 0-1,32-33

proxy:
  enabled: false
  http:
  https:
  noproxy:

pull_secret: /root/pull-secret.json
ssh_key: /root/.ssh/id_rsa.pub
ssh_priv_key: /root/.ssh/id_ed25519

#set it in a disconnected env
additional_trust_bundle: /root/registry/ca-bundle.crt
#set it in a disconnected env, mirror/mirror-operators.sh can be used to generate the file
container_registry:
  image_source: /root/registry/local-mirror.yaml
  catalog_sources:
    defaults:
      #- redhat-marketplace
      #- community-operators
      - certified-operators
      - redhat-operators
    customs:
      - name: prega
        display: Red Hat Operators OCP_Y_RELEASE PreGA
        image: quay.io/prega/prega-operator-index:vOCP_Y_RELEASE
        publisher: Red Hat
  icsp:
    - templates/day1/icsp/prega-OCP_Y_RELEASE.yaml

bmc:
  address: 192.168.13.148
  username: Administrator
  password: dummy
  kvm_uuid:
  
iso:
  address: http://192.168.58.15/iso/sno148.iso
  #optional, when mounting the virtual media, some hardware or redfish version may not support TransferProtocolType
  #in the API request, in that case set it as 'skip'
  #protocol: skip
  # deploy script will be called before mounting the ISO
  # arg1: generated ISO
  # arg2: .iso.address
  deploy: ${HOME}/bin/deploy_boot_iso.sh
