apiVersion: tuned.openshift.io/v1
kind: Tuned
metadata:
  name: performance-patch-kdump-setting
  namespace: openshift-cluster-node-tuning-operator
spec:
  profile:
  - data: |
      [main]
      summary=Configuration changes profile inherited from performance created tuned
      include=performance-patch
      [sysctl]
      kernel.sysrq=1
      kernel.panic_on_oops=1
      kernel.hung_task_panic=1
      kernel.hung_task_timeout_secs=120
    name: performance-patch-kdump-setting
  recommend:
  - machineConfigLabels:
      machineconfiguration.openshift.io/role: master
    priority: 18
    profile: performance-patch-kdump-setting